from __future__ import annotations

from typing import Any, Dict, Optional
from django.conf import settings
from rest_framework import serializers
from .models import Product, Category


class CategorySerializer(serializers.ModelSerializer):
    """Serializer for Category model with slug support.
    
    Handles serialization/deserialization of product categories.
    Slug is auto-generated by the model's save() method.
    """
    
    class Meta:
        model: type[Category] = Category
        fields: list[str] = ["id", "name", "slug"]
        read_only_fields: list[str] = ["slug"]


class ProductSerializer(serializers.ModelSerializer):
    """Serializer for Product model with enhanced image handling.
    
    Features:
    - Absolute image URLs in API responses
    - Category name included for display purposes
    - Automatic slug and timestamp generation via model
    - Reads binary image files, writes as multipart/form-data
    """

    category_name: serializers.SerializerMethodField = serializers.ReadOnlyField(
        source="category.name",
        help_text="Display name of the product category"
    )

    class Meta:
        model: type[Product] = Product
        fields: list[str] = [
            "id",
            "sku",
            "name",
            "slug",
            "description",
            "price",
            "size",
            "stock_quantity",
            "is_available",
            "image",
            "category",
            "category_name",
            "created_at",
            "updated_at",
        ]
        read_only_fields: list[str] = ["slug", "created_at", "updated_at"]
        extra_kwargs: Dict[str, Any] = {
            "image": {"required": False, "allow_null": True},
            "price": {"decimal_places": 2},
        }

    def to_representation(self, instance: Product) -> Dict[str, Any]:
        """Convert instance to dictionary with absolute image URLs.
        
        Args:
            instance: Product instance to serialize
            
        Returns:
            Dictionary with all product fields and absolute image URL
        """
        data: Dict[str, Any] = super().to_representation(instance)
        
        if instance.image:
            path: str = instance.image.url
            request: Optional[Any] = self.context.get("request")
            
            if request is not None:
                data["image"] = request.build_absolute_uri(path)
            else:
                # Fallback to settings-based URL construction
                base: str = (getattr(settings, "PUBLIC_BASE_URL", "") or "").rstrip("/")
                data["image"] = (
                    f"{base}{path}" if path.startswith("/") else f"{base}/{path}"
                ) if base else path
        else:
            data["image"] = None
        
        return data