# Generated by Django 6.0.2 on 2026-04-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Product category (deletes protected)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="api.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Complete description for online storefront"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True, help_text="E.g: S, M, L or 42, 44", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Unique product code (SKU/Barcode)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
