# Generated by Django 6.0.2 on 2026-04-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_product_category_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional category description", null=True
            ),
        ),
    ]
