# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_productgalleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_reference", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="prepared",
                        max_length=16,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=32)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("delivery", "Delivery"), ("pickup", "Pickup")],
                        max_length=16,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("pix", "Pix"), ("card", "Card"), ("cash", "Cash")],
                        max_length=16,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("neighborhood", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("message", models.TextField(blank=True)),
                ("whatsapp_url", models.URLField(blank=True, max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.saleorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_items",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
