# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_saleorder_saleorderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRegion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "neighborhoods",
                    models.TextField(blank=True, help_text="Optional comma-separated neighborhood hints"),
                ),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="saleorder",
            name="delivery_region_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="delivery_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="api.deliveryregion",
            ),
        ),
    ]
