# Generated by Django 6.0.2 on 2026-05-05 00:55

import bipdelivery.api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_storesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=bipdelivery.api.models.generate_bot_session_id, help_text='Public opaque identifier used by clients to continue the conversation.', max_length=64, unique=True)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp')], default='web', max_length=16)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_customer', 'Waiting customer'), ('waiting_human', 'Waiting human'), ('closed', 'Closed')], default='open', max_length=24)),
                ('last_intent', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['channel', 'status'], name='api_botconv_channel_0719b9_idx'), models.Index(fields=['last_intent'], name='api_botconv_last_in_1cec42_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=16)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.botconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='api_botmess_convers_798daf_idx'), models.Index(fields=['role'], name='api_botmess_role_a20f24_idx')],
            },
        ),
    ]
