# Generated by Django 6.0.2 on 2026-06-18 16:23

import django.db.models.deletion
from django.db import migrations, models

# Hardcoded, not bipdelivery.api.models.get_default_store_id: that callable
# calls Store.get_default(), which queries the *live* Store model -- every
# field defined today, not just the ones this migration's actual table has
# so far. Replaying migrations on a fresh DB (CI, a new install) hits it
# before 0030 adds receipt_exchange_policy/receipt_paper_format, and Django
# still SELECTs the full live column list, raising "no such column". The
# singleton default store already exists by this point (0013_backfill_
# default_store.py creates it through the frozen historical model) and,
# being the first-ever row in api_store, always gets PK 1 on a fresh DB.
DEFAULT_STORE_ID = 1


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_store_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                default=DEFAULT_STORE_ID,
                help_text="Tenant that owns this category (Etapa 2 of the multi-tenant evolution).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="api.store",
            ),
        ),
        migrations.AddField(
            model_name="deliveryregion",
            name="store",
            field=models.ForeignKey(
                default=DEFAULT_STORE_ID,
                help_text="Tenant that owns this delivery region (Etapa 2 of the multi-tenant evolution).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_regions",
                to="api.store",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                default=DEFAULT_STORE_ID,
                help_text="Tenant that owns this product (Etapa 2 of the multi-tenant evolution).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="api.store",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="store",
            field=models.ForeignKey(
                default=DEFAULT_STORE_ID,
                help_text="Tenant that received this order (Etapa 2 of the multi-tenant evolution).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.store",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryregion",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Unique product code (SKU/Barcode)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"), name="unique_category_slug_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryregion",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="unique_delivery_region_name_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store", "sku"), name="unique_product_sku_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"), name="unique_product_slug_per_store"
            ),
        ),
    ]
