# Generated by Django 6.0.2 on 2026-06-18 22:35

import bipdelivery.api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_category_store_deliveryregion_store_product_store_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=bipdelivery.api.models.product_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimage",
            name="image",
            field=models.ImageField(
                upload_to=bipdelivery.api.models.product_gallery_image_upload_to
            ),
        ),
    ]
