# Generated by Django 6.0.2 on 2026-06-22 16:27

import django.db.models.deletion
from django.db import migrations, models

# See 0015_category_store_deliveryregion_store_product_store_and_more.py's
# DEFAULT_STORE_ID comment: a live get_default_store_id() call here breaks
# replaying migrations on a fresh DB.
DEFAULT_STORE_ID = 1


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_product_image_alter_productgalleryimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="botconversation",
            name="sale_order",
            field=models.ForeignKey(
                blank=True,
                help_text="The order this conversation converted into, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bot_conversations",
                to="api.saleorder",
            ),
        ),
        migrations.AddField(
            model_name="botconversation",
            name="store",
            field=models.ForeignKey(
                default=DEFAULT_STORE_ID,
                help_text="Tenant this conversation belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_conversations",
                to="api.store",
            ),
        ),
    ]
