# Generated by Django 6.0.2 on 2026-06-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_botconversation_sale_order_botconversation_store"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(
                fields=["store", "created_at"], name="api_saleord_store_i_b6d9b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(
                fields=["store", "status", "created_at"],
                name="api_saleord_store_i_1efe9d_idx",
            ),
        ),
    ]
