# Generated by Django 6.0.2 on 2026-06-24 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_saleorder_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Normalized (lowercased) submitted username/email.",
                        max_length=255,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("succeeded", models.BooleanField(default=False)),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_credentials", "Invalid credentials"),
                            ("throttled", "Throttled"),
                            ("captcha_required", "Captcha required or invalid"),
                            ("mfa_required", "MFA challenge issued"),
                            ("mfa_invalid", "MFA code invalid"),
                        ],
                        max_length=32,
                    ),
                ),
                ("store_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved user, when the submitted identifier matched one. Null for unknown emails.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["identifier", "created_at"],
                        name="api_loginat_identif_b1682e_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="api_loginat_ip_addr_dbcac9_idx",
                    ),
                ],
            },
        ),
    ]
