# Generated by Django 6.0.2 on 2026-06-26 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# See 0015_category_store_deliveryregion_store_product_store_and_more.py's
# DEFAULT_STORE_ID comment: a live get_default_store_id() call here breaks
# replaying migrations on a fresh DB.
DEFAULT_STORE_ID = 1


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_mfa_totp_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Always positive; direction comes from movement_type."
                    ),
                ),
                ("previous_stock", models.PositiveIntegerField()),
                ("new_stock", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("compra", "Compra"),
                            ("devolucao", "Devolução"),
                            ("perda_avaria", "Perda/Avaria"),
                            ("ajuste_inventario", "Ajuste de inventário"),
                            ("entrada_inicial", "Entrada inicial"),
                            ("venda", "Venda"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("venda", "Venda")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="api.product",
                    ),
                ),
                (
                    "sale_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="api.saleorder",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        default=DEFAULT_STORE_ID,
                        help_text="Tenant that owns this movement.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="api.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "product", "created_at"],
                        name="api_stockmo_store_i_254179_idx",
                    ),
                    models.Index(
                        fields=["store", "created_at"],
                        name="api_stockmo_store_i_e166b7_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("new_stock__gte", 0)),
                        name="stock_movement_new_stock_non_negative",
                    )
                ],
            },
        ),
    ]
