# Generated by Django 6.0.2 on 2026-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_stock_movement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Per-product low-stock alert threshold (Etapa 3 of the stock-movement evolution). Null means "use the dashboard\'s default threshold" -- this is a preference, not an audited quantity, so unlike stock_quantity it stays freely editable.',
                null=True,
            ),
        ),
    ]
