# Generated by Django 6.0.2 on 2026-07-02
#
# Etapa 1 of the QR-code stock-exit evolution (see
# docs/architecture/qrcode-stock-exit-evolution.md). Split into three steps
# (add field -> backfill -> add constraint) so the unique constraint never
# has to reconcile duplicate blank values from existing rows: this step only
# adds the column.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_code',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text=(
                    'Auto-generated, immutable lookup code used by QR Code scans '
                    '(PDV and public storefront deep links, see '
                    'docs/architecture/qrcode-stock-exit-evolution.md). Distinct '
                    'from `sku`, which stays a manual, optional field the '
                    'merchant controls.'
                ),
                max_length=12,
            ),
        ),
    ]
