# Generated by Django 6.0.2 on 2026-07-02
#
# Etapa 1 of the QR-code stock-exit evolution: adds the uniqueness guarantee
# only after 0024 has backfilled every pre-existing row, so this can never
# fail against leftover duplicate blank values.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_backfill_product_public_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(
                fields=('store', 'public_code'), name='unique_product_public_code_per_store'
            ),
        ),
    ]
