# Generated by Django 6.0.2 on 2026-07-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_product_public_code_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="channel",
            field=models.CharField(
                choices=[("virtual", "Virtual"), ("loja_fisica", "Loja física")],
                default="virtual",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("venda", "Venda"), ("pdv", "PDV")],
                default="manual",
                max_length=10,
            ),
        ),
    ]
