# Generated by Django 6.0.2 on 2026-07-02 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_pdv_channel_and_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Etapa R3 of the QR-code stock-exit refinement: the dashboard operator who rang up this sale, when there is one -- always set for a PDV sale, always null for a public/WhatsApp checkout, which has no authenticated staff involved.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
