# Generated by Django 6.0.2 on 2026-07-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_saleorder_performed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("compra", "Compra"),
                    ("devolucao", "Devolução"),
                    ("perda_avaria", "Perda/Avaria"),
                    ("ajuste_inventario", "Ajuste de inventário"),
                    ("entrada_inicial", "Entrada inicial"),
                    ("venda", "Venda"),
                    ("venda_cancelada", "Venda cancelada"),
                    ("outro", "Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
