# Generated by Django 6.0.2 on 2026-07-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_customerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="receipt_exchange_policy",
            field=models.CharField(
                blank=True,
                default="Trocas e devoluções em até 7 dias mediante apresentação deste comprovante.",
                max_length=280,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="receipt_paper_format",
            field=models.CharField(
                choices=[
                    ("58mm", "Bobina 58mm"),
                    ("80mm", "Bobina 80mm"),
                    ("a4", "Folha A4"),
                ],
                default="80mm",
                max_length=10,
            ),
        ),
    ]
