# Generated by Django 6.0.2 on 2026-07-06 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_store_receipt_exchange_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="delivery_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_profiles",
                to="api.deliveryregion",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="customer_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the order was placed by an authenticated storefront customer (see docs/architecture/customer-profile-checkout-evolution.md); always null for pre-existing orders and for PDV sales, which have no customer account involved.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="api.customerprofile",
            ),
        ),
    ]
