# Generated by Django 6.0.2 on 2026-07-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_customerprofile_address_customerprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="carrier_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="tracking_url",
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("prepared", "Prepared"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="prepared",
                max_length=16,
            ),
        ),
    ]
