# Generated by Django 6.0.2 on 2026-07-10 02:18

import bipdelivery.api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_sale_order_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botconversation",
            name="store",
            field=models.ForeignKey(
                default=bipdelivery.api.models.get_default_store_id,
                help_text="Tenant this conversation belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_conversations",
                to="api.store",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                default=bipdelivery.api.models.get_default_store_id,
                help_text="Tenant that owns this category (Etapa 2 of the multi-tenant evolution).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="api.store",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryregion",
            name="store",
            field=models.ForeignKey(
                default=bipdelivery.api.models.get_default_store_id,
                help_text="Tenant that owns this delivery region (Etapa 2 of the multi-tenant evolution).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_regions",
                to="api.store",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                default=bipdelivery.api.models.get_default_store_id,
                help_text="Tenant that owns this product (Etapa 2 of the multi-tenant evolution).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="api.store",
            ),
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="store",
            field=models.ForeignKey(
                default=bipdelivery.api.models.get_default_store_id,
                help_text="Tenant that received this order (Etapa 2 of the multi-tenant evolution).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.store",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="store",
            field=models.ForeignKey(
                default=bipdelivery.api.models.get_default_store_id,
                help_text="Tenant that owns this movement.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="api.store",
            ),
        ),
    ]
