# Generated by Django 6.0.2 on 2026-08-15 02:38

from django.db import migrations, models


def backfill_payment_tracking(apps, schema_editor):
    SaleOrder = apps.get_model("api", "SaleOrder")

    SaleOrder.objects.filter(channel="loja_fisica").update(
        payment_status="confirmed",
        payment_display_code="Pagamento registrado no PDV",
        payment_instructions="Pagamento registrado no PDV da loja.",
    )
    SaleOrder.objects.filter(channel="virtual", payment_method="cash").update(
        payment_status="pay_at_store",
        payment_display_code="Pagamento na loja",
        payment_instructions="Pagamento em dinheiro apenas na loja.",
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_product_auto_sku_from_public_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='payment_display_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pay_at_store', 'Pay at store'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_payment_tracking, noop_reverse),
    ]
