# Generated by Django 6.0.7 on 2026-08-23 16:21

import bipdelivery.api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_product_auto_sku_from_public_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='variant_color_hex',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='variant_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color_hex', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to=bipdelivery.api.models.product_variant_image_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='api.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_variant_name_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'position'), name='unique_product_variant_position_per_product'),
        ),
    ]
