# Generated by Django 6.0.7 on 2026-08-15 11:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_saleorder_payment_display_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='payment_installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_installment_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_installments',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_link_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='store',
            name='card_max_installments',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='store',
            name='card_min_installment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Smallest allowed simulated card installment amount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='card_monthly_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly percentage used only for card installment simulation.', max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_card_link_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_pix_link_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
