# Generated by Codex on 2026-08-23

from django.db import migrations, models


def backfill_variant_stock_from_product(apps, schema_editor):
    ProductVariant = apps.get_model("api", "ProductVariant")

    batch = []
    for variant in (
        ProductVariant.objects.select_related("product")
        .only("id", "stock_quantity", "product__stock_quantity")
        .iterator(chunk_size=500)
    ):
        variant.stock_quantity = variant.product.stock_quantity
        batch.append(variant)

        if len(batch) >= 500:
            ProductVariant.objects.bulk_update(batch, ["stock_quantity"])
            batch = []

    if batch:
        ProductVariant.objects.bulk_update(batch, ["stock_quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_saleorderitem_variant_color_hex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_variant_stock_from_product, migrations.RunPython.noop),
    ]
