# Generated by Django 6.0.7 on 2026-08-23 22:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_productvariant_stock_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_format",
                    models.CharField(
                        choices=[("a4", "A4")], default="a4", max_length=8
                    ),
                ),
                (
                    "columns",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "rows",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "margin_mm",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "cell_padding_mm",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "qr_size_mm",
                    models.PositiveSmallIntegerField(
                        default=26,
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(80),
                        ],
                    ),
                ),
                ("show_price", models.BooleanField(default=True)),
                ("show_size", models.BooleanField(default=True)),
                ("show_public_code", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Label settings",
                "verbose_name_plural": "Label settings",
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="api.productvariant",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["store", "variant", "created_at"],
                name="api_stockmo_store_i_8b7b37_idx",
            ),
        ),
        migrations.AddField(
            model_name="labelsettings",
            name="store",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_settings",
                to="api.store",
            ),
        ),
    ]
