# Generated by Django 6.0.7 on 2026-08-15 11:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_payment_gateway_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='saleorder',
            constraint=models.CheckConstraint(condition=models.Q(('payment_installments__gte', 1), ('payment_installments__lte', 24)), name='saleorder_payment_installments_range'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('card_max_installments__gte', 1), ('card_max_installments__lte', 24)), name='store_card_max_installments_range'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('card_monthly_interest_rate__gte', Decimal('0.00')), ('card_monthly_interest_rate__lte', Decimal('30.00'))), name='store_card_monthly_interest_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('card_min_installment_amount__gte', Decimal('1.00'))), name='store_card_min_installment_amount_min'),
        ),
    ]
