# Generated by Django 6.0.2 on 2026-08-24 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Depends on the last *committed* migration, not the uncommitted
        # 0038 (unrelated in-progress category work) also on disk -- keeps
        # this branch's migration history self-consistent on its own.
        ('api', '0037_labelsettings_stockmovement_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('hero_enabled', models.BooleanField(default=False)),
                ('hero_image_desktop', models.URLField(blank=True, max_length=500)),
                ('hero_image_mobile', models.URLField(blank=True, max_length=500)),
                ('hero_alt_text', models.CharField(blank=True, max_length=160)),
                ('hero_title', models.CharField(blank=True, max_length=120)),
                ('hero_subtitle', models.CharField(blank=True, max_length=200)),
                ('hero_cta_text', models.CharField(blank=True, max_length=40)),
                ('hero_cta_url', models.URLField(blank=True, max_length=500)),
                ('card_style', models.CharField(choices=[('clean', 'Clean'), ('bordered', 'Bordered'), ('elevated', 'Elevated')], default='clean', max_length=16)),
                ('radius_style', models.CharField(choices=[('minimal', 'Minimal'), ('rounded', 'Rounded'), ('soft', 'Soft')], default='rounded', max_length=16)),
                ('density', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', max_length=16)),
                ('motion_enabled', models.BooleanField(default=True)),
                ('motion_intensity', models.CharField(choices=[('subtle', 'Subtle'), ('standard', 'Standard')], default='standard', max_length=16)),
                ('decoration_enabled', models.BooleanField(default=False)),
                ('decoration_style', models.CharField(choices=[('none', 'None'), ('circles', 'Circles'), ('soft-shapes', 'Soft shapes'), ('geometric', 'Geometric')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_appearance', to='api.store')),
            ],
            options={
                'verbose_name': 'Storefront appearance',
                'verbose_name_plural': 'Storefront appearance',
            },
        ),
    ]
