# Generated by Django 6.0.7 on 2026-08-24 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_storefront_appearance"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_slug_per_store",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent category for one-level subcategory organization.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="api.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("store", "slug"),
                name="unique_top_level_category_slug_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("store", "parent", "slug"),
                name="unique_subcategory_slug_per_parent",
            ),
        ),
    ]
