# Generated by Django 6.0.7 on 2026-08-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_category_parent_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontappearance',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='storefrontappearance',
            name='hero_destination_type',
            field=models.CharField(choices=[('none', 'Nenhuma acao'), ('products', 'Abrir vitrine'), ('category', 'Abrir categoria'), ('product', 'Abrir produto'), ('external_url', 'Abrir link externo')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='storefrontappearance',
            name='hero_destination_value',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='storefrontappearance',
            name='hero_cta_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='StorefrontBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('cta_text', models.CharField(blank=True, max_length=40)),
                ('destination_type', models.CharField(choices=[('none', 'Nenhuma acao'), ('products', 'Abrir vitrine'), ('category', 'Abrir categoria'), ('product', 'Abrir produto'), ('external_url', 'Abrir link externo')], default='none', max_length=16)),
                ('destination_value', models.CharField(blank=True, max_length=500)),
                ('button_url', models.CharField(blank=True, max_length=500)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_banners', to='api.store')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['store', 'position'], name='api_storefr_store_i_254068_idx'), models.Index(fields=['store', 'is_active', 'starts_at', 'ends_at'], name='api_storefr_store_i_80c614_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('starts_at__lte', models.F('ends_at')), _connector='OR'), name='storefront_banner_valid_schedule')],
            },
        ),
    ]
