# Generated by Django 6.0.7 on 2026-08-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_storefrontappearance_favicon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='storefrontappearance',
            name='font_preset',
            field=models.CharField(choices=[('modern', 'Modern'), ('editorial', 'Editorial'), ('classic', 'Classic')], default='modern', max_length=16),
        ),
    ]
