# Generated by Django 6.0.2 on 2026-08-28 18:01

import bipdelivery.api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_saleorder_idempotency"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("problem", "Problema"),
                            ("purchase_difficulty", "Dificuldade na compra"),
                            ("shipping", "Entrega/Frete"),
                            ("checkout", "Checkout"),
                            ("product", "Produto"),
                            ("suggestion", "Sugestao"),
                            ("other", "Outro"),
                        ],
                        max_length=24,
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Optional WhatsApp/e-mail the customer left for a reply.",
                        max_length=160,
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        blank=True,
                        help_text="Storefront route the report was opened from, not a full URL.",
                        max_length=512,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        help_text="X-Request-ID of the failed request this feedback is about, when known.",
                        max_length=64,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("reviewing", "Em analise"),
                            ("resolved", "Resolvido"),
                            ("ignored", "Ignorado"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved automatically from the authenticated session, when there is one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="api.customerprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="api.saleorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="api.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        default=bipdelivery.api.models.get_default_store_id,
                        help_text="Tenant this feedback was submitted to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_feedback",
                        to="api.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "status", "created_at"],
                        name="api_custome_store_i_5b7203_idx",
                    ),
                    models.Index(
                        fields=["store", "feedback_type", "created_at"],
                        name="api_custome_store_i_c77c7f_idx",
                    ),
                ],
            },
        ),
    ]
