# Generated by Django 6.0.2 on 2026-08-28 22:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_customer_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional per-variant price override. NULL (the default) means this variant inherits Product.price -- semantically different from 0.00. Resolve the effective price via Product.get_effective_price(variant), never variant.price directly.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
