# Generated by Django 6.0.2 on 2026-09-02 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0046_product_variant_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, help_text="Razao social", max_length=160
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, help_text="Nome fantasia", max_length=160
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="CPF (11 digitos) ou CNPJ (14). Armazenado somente com digitos.",
                        max_length=14,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone comercial, somente digitos (DDI+DDD+numero).",
                        max_length=13,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="CEP, somente digitos", max_length=8
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=160)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("complement", models.CharField(blank=True, max_length=80)),
                (
                    "district",
                    models.CharField(blank=True, help_text="Bairro", max_length=80),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        help_text="UF",
                        max_length=2,
                    ),
                ),
                ("country", models.CharField(default="BR", max_length=2)),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "tiktok_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_profile",
                        to="api.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant profile",
                "verbose_name_plural": "Merchant profiles",
            },
        ),
    ]
