<script setup lang="ts">
import { computed, ref } from 'vue';
import { CheckIcon, ChevronDownIcon, ClipboardDocumentIcon } from '@heroicons/vue/24/outline';
import FormInput from '@/components/common/FormInput.vue';
import { useToast } from '@/composables/useToast';

const name = defineModel<string>('name', { default: '' });
const sku = defineModel<string>('sku', { default: '' });
const description = defineModel<string>('description', { default: '' });
const category = defineModel<string | number | null>('category', { default: null });

interface Props {
  categories: Array<{ id: number; name: string }>;
  errors: Record<string, string[]>;
  // Read-only: generated by the backend on creation (Etapa 1 of the QR-code
  // stock-exit evolution) and never editable from this form -- distinct
  // from `sku`, which stays a manual field the merchant controls above.
  publicCode?: string | null;
}

const props = defineProps<Props>();

const toast = useToast();

const copyPublicCode = async (): Promise<void> => {
  if (!props.publicCode) {
    return;
  }

  try {
    await navigator.clipboard.writeText(props.publicCode);
    toast.success('Código copiado.');
  } catch {
    toast.error('Não foi possível copiar o código.');
  }
};

const isCategoryMenuOpen = ref(false);

const selectedCategoryName = computed(() => {
  const selectedCategory = props.categories.find((item) => item.id === Number(category.value));
  return selectedCategory?.name ?? 'Selecionar categoria';
});

const isSelectedCategory = (categoryId: number) => Number(category.value) === categoryId;

const toggleCategoryMenu = () => {
  if (!props.categories.length) {
    return;
  }

  isCategoryMenuOpen.value = !isCategoryMenuOpen.value;
};

const selectCategory = (categoryId: number) => {
  category.value = categoryId;
  isCategoryMenuOpen.value = false;
};

const handleCategoryFocusOut = (event: FocusEvent) => {
  const wrapper = event.currentTarget as HTMLElement;

  requestAnimationFrame(() => {
    if (!wrapper.contains(document.activeElement)) {
      isCategoryMenuOpen.value = false;
    }
  });
};
</script>

<template>
  <section class="space-y-8 border-b border-[#E5E7EB] pb-10" @click="isCategoryMenuOpen = false">
    <header>
      <h3 class="mb-1 text-[10px] font-black uppercase tracking-[0.3em] text-[#D81B60]">
        Identidade do produto
      </h3>
      <p class="text-[9px] font-bold uppercase tracking-widest text-bip-muted">
        Dados que aparecem na vitrine pública
      </p>
    </header>

    <FormInput
      v-model="name"
      label="Nome do produto"
      name="name"
      data-cy="input-product-name"
      placeholder="Ex.: Combo artesanal"
      :error="errors.name?.[0]"
    />

    <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
      <FormInput
        v-model="sku"
        label="SKU"
        name="sku"
        data-cy="input-product-sku"
        placeholder="BPF-001"
        :error="errors.sku?.[0]"
      />

      <div class="group flex flex-col">
        <label class="mb-2 text-[10px] font-black uppercase tracking-[0.2em] text-bip-muted transition-colors group-focus-within:text-[#D81B60]">
          Categoria
        </label>

        <div class="relative" @click.stop @focusout="handleCategoryFocusOut">
          <input type="hidden" name="category" :value="category ?? ''" />
          <button
            type="button"
            data-cy="select-category"
            :aria-expanded="isCategoryMenuOpen"
            aria-haspopup="listbox"
            aria-controls="product-category-menu"
            class="flex h-12 w-full items-center justify-between gap-3 rounded-xl border px-4 text-left text-sm transition-all"
            :class="[
              errors.category
                ? 'border-[#D81B60]/50 bg-[#FCE7F3] text-[#7A143D]'
                : 'border-[#D1D5DB] bg-white text-[#05050A] hover:border-[#D81B60]/40',
              isCategoryMenuOpen ? 'border-[#D81B60] ring-2 ring-[#FCE7F3]' : ''
            ]"
            @click="toggleCategoryMenu"
          >
            <span class="truncate" :class="{ 'text-bip-muted': !category }">
              {{ categories.length ? selectedCategoryName : 'Nenhuma categoria cadastrada' }}
            </span>
            <ChevronDownIcon
              class="h-4 w-4 shrink-0 text-bip-muted transition-transform"
              :class="{ 'rotate-180 text-[#D81B60]': isCategoryMenuOpen }"
            />
          </button>

          <Transition name="category-popover">
            <div
              v-if="isCategoryMenuOpen"
              id="product-category-menu"
              role="listbox"
              class="category-menu-scroll absolute left-0 right-0 top-[calc(100%+0.5rem)] z-40 max-h-60 overflow-y-auto rounded-xl border border-[#E5E7EB] bg-white p-1 shadow-2xl shadow-black/10"
            >
              <button
                v-for="item in categories"
                :key="item.id"
                type="button"
                role="option"
                :aria-selected="isSelectedCategory(item.id)"
                :data-cy="`category-option-${item.id}`"
                class="flex h-10 w-full items-center justify-between gap-3 rounded-lg px-3 text-left text-xs font-semibold text-bip-muted transition hover:bg-zinc-50 hover:text-[#05050A]"
                :class="{ 'bg-[#FCE7F3] text-[#05050A]': isSelectedCategory(item.id) }"
                @click="selectCategory(item.id)"
              >
                <span class="truncate">{{ item.name }}</span>
                <CheckIcon v-if="isSelectedCategory(item.id)" class="h-4 w-4 shrink-0 text-[#D81B60]" />
              </button>
            </div>
          </Transition>
        </div>

        <p v-if="errors.category" class="mt-2 text-[9px] font-black uppercase tracking-widest text-[#D81B60]">
          {{ errors.category[0] }}
        </p>
      </div>
    </div>

    <div v-if="props.publicCode" class="group flex flex-col gap-2">
      <label class="text-[10px] font-black uppercase tracking-[0.2em] text-bip-muted">
        Código BipFlow
      </label>
      <div class="flex items-center gap-2">
        <input
          :value="props.publicCode"
          type="text"
          readonly
          data-cy="input-product-public-code"
          class="w-full rounded-xl border border-[#E5E7EB] bg-zinc-50 px-4 py-3 font-mono text-sm text-[#05050A] outline-none"
        />
        <button
          type="button"
          data-cy="btn-copy-public-code"
          title="Copiar código"
          class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border border-[#E5E7EB] bg-white text-bip-muted transition-colors hover:border-[#D81B60]/40 hover:bg-[#FCE7F3] hover:text-[#D81B60]"
          @click="copyPublicCode"
        >
          <ClipboardDocumentIcon class="h-4 w-4" />
        </button>
      </div>
      <p class="text-[9px] font-bold uppercase tracking-widest text-bip-muted">
        Gerado automaticamente pelo BipFlow. Usado para dar baixa por QR Code na loja física e virtual.
      </p>
    </div>

    <div class="group flex flex-col gap-2">
      <label class="text-[10px] font-black uppercase tracking-[0.2em] text-bip-muted transition-colors group-focus-within:text-[#D81B60]">
        Descrição pública
      </label>
      <textarea
        v-model="description"
        name="description"
        data-cy="input-product-description"
        rows="4"
        class="w-full resize-none rounded-xl border border-[#D1D5DB] bg-white px-4 py-3 text-sm text-[#05050A] outline-none transition-all placeholder:text-bip-muted/70 focus:border-[#D81B60] focus:ring-2 focus:ring-[#FCE7F3]"
        placeholder="Descreva o produto para a vitrine: ingredientes, materiais, diferenciais ou forma de uso."
      />
      <p v-if="errors.description" class="text-[9px] font-black uppercase tracking-widest text-[#D81B60]">
        {{ errors.description[0] }}
      </p>
    </div>
  </section>
</template>

<style scoped>
.category-popover-enter-active,
.category-popover-leave-active {
  transition: opacity 0.16s ease, transform 0.16s ease;
}

.category-popover-enter-from,
.category-popover-leave-to {
  opacity: 0;
  transform: translateY(-4px);
}

.category-menu-scroll::-webkit-scrollbar {
  width: 4px;
}

.category-menu-scroll::-webkit-scrollbar-thumb {
  background: #d1d5db;
  border-radius: 999px;
}
</style>
